/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.impressora;

import control.Sistema;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import model.*;
import view.Alertas;

/**
 *
 * @author Rafael
 */
public class ImpressoraCadastro extends javax.swing.JInternalFrame {

    Sistema sistema;
    ArrayList<Setor> listaSetores;
    ArrayList<ModeloImpressora> listaModelos;

    public ImpressoraCadastro(Sistema sistema) {
        this.sistema = sistema;
        initComponents();

        try {
            this.listaSetores = this.sistema.getListaDeSetores();
            this.listaModelos = this.sistema.getListaDeModelosImpressoras();
            if (!listaSetores.isEmpty() && !listaModelos.isEmpty()) {
                
                String[] setores = new String[this.listaSetores.size()];
                for (int i = 0; i < this.listaSetores.size(); i++) {
                    setores[i] = listaSetores.get(i).getNome() + " (" + listaSetores.get(i).getEmpresa() + ")";
                }
                
                String[] modelos = new String[this.listaModelos.size()];
                for (int i = 0; i < this.listaModelos.size(); i++) {
                    modelos[i] = listaModelos.get(i).getModeloImpressora();
                }
                
                DefaultComboBoxModel modelS = new DefaultComboBoxModel(setores);
                this.jComboBoxSetor.setModel(modelS);
                
                DefaultComboBoxModel modelM = new DefaultComboBoxModel(modelos);
                this.jComboBoxModelo.setModel(modelM);
            }
        } catch (SQLException ex) {
            Alertas.erroBanco(this,ex.toString());
        }
}

/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBoxSetor = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabelCodigo = new javax.swing.JLabel();
        jTextCodigo = new javax.swing.JTextField();
        jComboBoxModelo = new javax.swing.JComboBox<>();
        jComboBoxTipo = new javax.swing.JComboBox<>();

        setClosable(true);
        setTitle("Cadastrar Nova Impressora");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setText("Setor:");

        jLabel2.setText("Modelo:");

        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Tipo:");

        jLabelCodigo.setText("Tombo:");

        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Consignado", "Próprio" }));
        jComboBoxTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxTipoItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxSetor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxModelo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabelCodigo))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxTipo, 0, 173, Short.MAX_VALUE)
                            .addComponent(jTextCodigo))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodigo)
                    .addComponent(jTextCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jButton1)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean sucesso = false;
        
        try{
            Impressora x = new Impressora();
            x.setIdSetor(listaSetores.get(this.jComboBoxSetor.getSelectedIndex()).getId());
            x.setIdModeloImpressora(listaModelos.get(this.jComboBoxModelo.getSelectedIndex()).getId());
            x.setTipo(this.jComboBoxTipo.getSelectedItem().toString());
            x.setCodigo(this.jTextCodigo.getText());
            try {
                sucesso = this.sistema.cadastrarImpressora(x);
            } catch (SQLException ex) {
                Alertas.erroBanco(this,ex.toString());
            }
            
        }catch (NumberFormatException e){
            Alertas.erroFormatoEntrada(this);
        }
        Alertas.sucessoOuErro(this,sucesso);
        if(sucesso) this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        if(listaSetores.isEmpty()){
            Alertas.mensagem(this, "É preciso cadastrar um setor!");
            this.dispose();
        }else if(listaModelos.isEmpty()){
            Alertas.mensagem(this, "É preciso cadastrar um modelo de impressora!");
            this.dispose();
        }
    }//GEN-LAST:event_formComponentShown

    private void jComboBoxTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxTipoItemStateChanged
        int index = this.jComboBoxTipo.getSelectedIndex();
        if(index==0) this.jLabelCodigo.setText("Serial:");
        else this.jLabelCodigo.setText("Tombo:");
    }//GEN-LAST:event_jComboBoxTipoItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxModelo;
    private javax.swing.JComboBox<String> jComboBoxSetor;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JTextField jTextCodigo;
    // End of variables declaration//GEN-END:variables
}
