/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.movimentacoes;

import control.Sistema;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import model.*;
import view.Alertas;

/**
 *
 * @author Rafael
 */
public class MovimentacoesSaida extends javax.swing.JInternalFrame {

    Sistema sistema;
    ArrayList<Toner> listaToner;
    ArrayList<Setor> listaSetor;
    
    public MovimentacoesSaida(Sistema sistema) {
        this.sistema = sistema;
        initComponents();
        
        this.listaToner = this.sistema.getListaDeToner();
        if (!listaToner.isEmpty()) {
            String[] toners = new String[this.listaToner.size()];
            for (int i = 0; i < this.listaToner.size(); i++) {
                Impressora imp = this.sistema.getImpressora(this.listaToner.get(i).getIdImpressora());
                toners[i] = imp.getModeloToner() + " ("+listaToner.get(i).getTipo()+") - "+imp.getModelo();
            }
            DefaultComboBoxModel model = new DefaultComboBoxModel(toners);
            this.jComboBoxToner.setModel(model);
        }
        
        this.listaSetor = this.sistema.getListaDeSetores();
        if (!listaSetor.isEmpty()) {
            String[] setores = new String[this.listaSetor.size()];
            for (int i = 0; i < this.listaSetor.size(); i++) {
                setores[i] = listaSetor.get(i).getNome()+" - "+listaSetor.get(i).getEmpresa();
            }
            DefaultComboBoxModel model = new DefaultComboBoxModel(setores);
            this.jComboBoxSetor.setModel(model);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextCheio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextVazio = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxToner = new javax.swing.JComboBox<>();
        jComboBoxSetor = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Nova Saída");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jTextCheio.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextCheio.setText("0");

        jLabel1.setText("Qtd. cheio:");

        jLabel2.setText("Qtd. vazio:");

        jTextVazio.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextVazio.setText("0");

        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Toner:");

        jLabel4.setText("Setor:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel4))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jComboBoxSetor, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jTextCheio, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextVazio, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(32, 32, 32)
                            .addComponent(jComboBoxToner, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxToner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jTextCheio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextVazio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBounds(300, 100, 294, 157);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean sucesso = false;
        try{
            int cheio = Integer.parseInt(this.jTextCheio.getText());
            int vazio = Integer.parseInt(this.jTextVazio.getText());
            String hoje = new SimpleDateFormat("yyyy-MM-dd").format(Calendar.getInstance().getTime());
            Saida x = new Saida();
            x.setIdToner(listaToner.get(this.jComboBoxToner.getSelectedIndex()).getId());
            x.setIdUsuario(this.sistema.getIdUsuarioAtivo());
            x.setQtdCheio(cheio);
            x.setQtdVazio(vazio);
            x.setData(hoje);
            x.setIdSetor(listaSetor.get(this.jComboBoxSetor.getSelectedIndex()).getId());

            sucesso = this.sistema.cadastrarSaida(x);
            
        }catch (NumberFormatException e){
            sucesso = false;
        }finally{
            Alertas.sucessoOuErro(this,sucesso);
            if(sucesso) this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        if(listaToner.isEmpty() || listaSetor.isEmpty()){
            Alertas.mensagem(this, "É preciso cadastrar um toner!");
            this.dispose();
        }
    }//GEN-LAST:event_formComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxSetor;
    private javax.swing.JComboBox<String> jComboBoxToner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextCheio;
    private javax.swing.JTextField jTextVazio;
    // End of variables declaration//GEN-END:variables
}
