/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.TonerDAO;
import javax.swing.JOptionPane;
import model.Toner;

/**
 *
 * @author diegocruzalves
 */
public class JCadastrarToner extends javax.swing.JInternalFrame {

    /**
     * Creates new form JCadastrarToner
     */
    public JCadastrarToner() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idLabel = new javax.swing.JLabel();
        modelLabel = new javax.swing.JLabel();
        nsLabel = new javax.swing.JLabel();
        empresaLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bpLabel = new javax.swing.JLabel();
        tipotonerLabel = new javax.swing.JLabel();
        setorLabel = new javax.swing.JLabel();
        entId = new javax.swing.JTextField();
        entModelo = new javax.swing.JTextField();
        entNs = new javax.swing.JTextField();
        entBp = new javax.swing.JTextField();
        entEmpresa = new javax.swing.JTextField();
        entPreco = new javax.swing.JTextField();
        entTipoToner = new javax.swing.JComboBox<>();
        entSetor = new javax.swing.JTextField();
        entStatus = new javax.swing.JComboBox<>();
        entFabricante = new javax.swing.JTextField();
        btnGravar_cadToner = new javax.swing.JButton();
        btnCancelar_cadToner = new javax.swing.JButton();
        statusLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Cadastro de Toner");
        setToolTipText("");

        idLabel.setText("ID");
        idLabel.setBounds(new java.awt.Rectangle(10, 0, 0, 0));

        modelLabel.setText("Modelo");
        modelLabel.setBounds(new java.awt.Rectangle(10, 0, 0, 0));

        nsLabel.setText("Número de Série");
        nsLabel.setBounds(new java.awt.Rectangle(10, 0, 0, 0));

        empresaLabel.setText("Empresa");
        empresaLabel.setBounds(new java.awt.Rectangle(10, 0, 0, 0));

        jLabel6.setText("Preço");
        jLabel6.setBounds(new java.awt.Rectangle(10, 0, 0, 0));

        bpLabel.setText("Bem Patrimonial");
        bpLabel.setBounds(new java.awt.Rectangle(10, 0, 0, 0));

        tipotonerLabel.setText("Tipo do Toner");
        tipotonerLabel.setBounds(new java.awt.Rectangle(10, 0, 0, 0));

        setorLabel.setText("Setor");

        entId.setEnabled(false);
        entId.setSize(new java.awt.Dimension(100, 0));
        entId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entIdActionPerformed(evt);
            }
        });

        entModelo.setSize(new java.awt.Dimension(100, 0));

        entNs.setSize(new java.awt.Dimension(100, 0));

        entBp.setSize(new java.awt.Dimension(100, 0));

        entEmpresa.setSize(new java.awt.Dimension(100, 0));

        entPreco.setSize(new java.awt.Dimension(100, 0));

        entTipoToner.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Consignado", "Recarga" }));
        entTipoToner.setSize(new java.awt.Dimension(100, 0));
        entTipoToner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entTipoTonerActionPerformed(evt);
            }
        });

        entStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Novo" }));

        btnGravar_cadToner.setText("Gravar");
        btnGravar_cadToner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravar_cadTonerActionPerformed(evt);
            }
        });

        btnCancelar_cadToner.setText("Cancelar");
        btnCancelar_cadToner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar_cadTonerActionPerformed(evt);
            }
        });

        statusLabel.setText("Status");

        jLabel1.setText("Fabricante");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipotonerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(entId, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entNs, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entTipoToner, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(empresaLabel)
                            .addComponent(statusLabel)
                            .addComponent(bpLabel)
                            .addComponent(jLabel6)
                            .addComponent(setorLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(entStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entBp, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnGravar_cadToner)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar_cadToner)))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bpLabel, empresaLabel, idLabel, jLabel1, jLabel6, modelLabel, nsLabel, tipotonerLabel});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(entId, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setorLabel)
                    .addComponent(entSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(entFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(entPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(entModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bpLabel)
                    .addComponent(entBp, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(entNs, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empresaLabel)
                    .addComponent(entEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipotonerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(entTipoToner, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusLabel)
                    .addComponent(entStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar_cadToner)
                    .addComponent(btnGravar_cadToner))
                .addGap(17, 17, 17))
        );

        getAccessibleContext().setAccessibleName("Cadastrar de Toner");
        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entIdActionPerformed

    private void entTipoTonerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entTipoTonerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entTipoTonerActionPerformed

    private void btnGravar_cadTonerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravar_cadTonerActionPerformed
        Toner toner = new Toner();

        toner.setFabricante(entFabricante.getText());
        toner.setModelo(entModelo.getText());
        toner.setNum_serie(entNs.getText());
        toner.setBp(Integer.parseInt(entBp.getText()));
        toner.setSetor((entSetor.getText()));
        toner.setPreco(Double.parseDouble(entPreco.getText()));
        toner.setEmpresa((entEmpresa.getText()));
        toner.setTipoToner(entTipoToner.getSelectedItem().toString());
        toner.setStatus(entStatus.getSelectedItem().toString());

        // Validação de dados
        if ((entModelo.getText().isEmpty()) || (entNs.getText().isEmpty()) || (Integer.parseInt(entBp.getText()) == 0) || 
                (entEmpresa.getText().isEmpty()) || (Double.parseDouble(entPreco.getText()) == 0) || (entTipoToner.getSelectedItem().toString()).isEmpty()) {
            JOptionPane.showMessageDialog(null, "O preenchimento de todos os campos é obrigatório!");
        } else { // instanciando a classe*/
            TonerDAO dao = new TonerDAO();
            dao.cadastrarToner(toner);
            JOptionPane.showMessageDialog(null, "Toner cadastrado com sucesso!");
        }

        entFabricante.setText("");
        entModelo.setText("");
        entNs.setText("");
        entBp.setText("");
        entSetor.setText("");
        entPreco.setText("");
        entEmpresa.setText("");
        entTipoToner.setSelectedItem("-");
        entStatus.setSelectedItem("Novo");
    }//GEN-LAST:event_btnGravar_cadTonerActionPerformed

    private void btnCancelar_cadTonerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar_cadTonerActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelar_cadTonerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bpLabel;
    private javax.swing.JButton btnCancelar_cadToner;
    private javax.swing.JButton btnGravar_cadToner;
    private javax.swing.JLabel empresaLabel;
    private javax.swing.JTextField entBp;
    private javax.swing.JTextField entEmpresa;
    private javax.swing.JTextField entFabricante;
    private javax.swing.JTextField entId;
    private javax.swing.JTextField entModelo;
    private javax.swing.JTextField entNs;
    private javax.swing.JTextField entPreco;
    private javax.swing.JTextField entSetor;
    private javax.swing.JComboBox<String> entStatus;
    private javax.swing.JComboBox<String> entTipoToner;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel modelLabel;
    private javax.swing.JLabel nsLabel;
    private javax.swing.JLabel setorLabel;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JLabel tipotonerLabel;
    // End of variables declaration//GEN-END:variables
}
