/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.TonerDAO;
import javax.swing.JOptionPane;
import model.Toner;

/**
 *
 * @author diegocruzalves
 */
public class JCadastrarToner extends javax.swing.JFrame {

    /**
     * Creates new form JCadastrarToner
     */
    public JCadastrarToner() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        entId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        entTipoToner = new javax.swing.JComboBox<>();
        entModelo = new javax.swing.JTextField();
        entNs = new javax.swing.JTextField();
        entBp = new javax.swing.JTextField();
        entEmpresa = new javax.swing.JTextField();
        entPreco = new javax.swing.JTextField();
        btnGravar_cadToner = new javax.swing.JButton();
        btnCancelar_cadToner = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Toner");
        setBounds(new java.awt.Rectangle(10, 0, 0, 0));
        setResizable(false);

        jLabel1.setText("ID");
        jLabel1.setBounds(new java.awt.Rectangle(10, 0, 0, 0));

        entId.setEnabled(false);
        entId.setSize(new java.awt.Dimension(100, 0));
        entId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entIdActionPerformed(evt);
            }
        });

        jLabel2.setText("Modelo");
        jLabel2.setBounds(new java.awt.Rectangle(10, 0, 0, 0));

        jLabel3.setText("Número de Série");
        jLabel3.setBounds(new java.awt.Rectangle(10, 0, 0, 0));

        jLabel4.setText("Bem Patrimonial");
        jLabel4.setBounds(new java.awt.Rectangle(10, 0, 0, 0));

        jLabel5.setText("Empresa");
        jLabel5.setBounds(new java.awt.Rectangle(10, 0, 0, 0));

        jLabel6.setText("Preço");
        jLabel6.setBounds(new java.awt.Rectangle(10, 0, 0, 0));

        jLabel7.setText("Tipo do Toner");
        jLabel7.setBounds(new java.awt.Rectangle(10, 0, 0, 0));

        entTipoToner.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Consignado", "Recarga" }));
        entTipoToner.setSize(new java.awt.Dimension(100, 0));
        entTipoToner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entTipoTonerActionPerformed(evt);
            }
        });

        entModelo.setSize(new java.awt.Dimension(100, 0));

        entNs.setSize(new java.awt.Dimension(100, 0));

        entBp.setSize(new java.awt.Dimension(100, 0));

        entEmpresa.setSize(new java.awt.Dimension(100, 0));

        entPreco.setSize(new java.awt.Dimension(100, 0));

        btnGravar_cadToner.setText("Gravar");
        btnGravar_cadToner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravar_cadTonerActionPerformed(evt);
            }
        });

        btnCancelar_cadToner.setText("Cancelar");
        btnCancelar_cadToner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar_cadTonerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(entNs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entBp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entTipoToner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entId, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 27, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnGravar_cadToner)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar_cadToner)
                        .addGap(73, 73, 73))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {entBp, entEmpresa, entId, entModelo, entNs, entPreco, entTipoToner});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCancelar_cadToner, btnGravar_cadToner});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(entId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(entModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(entNs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(entBp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(entEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(entPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(entTipoToner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGravar_cadToner)
                    .addComponent(btnCancelar_cadToner))
                .addGap(18, 18, 18))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {entBp, entEmpresa, entId, entModelo, entNs, entPreco, entTipoToner});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void entIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entIdActionPerformed

    private void entTipoTonerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entTipoTonerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entTipoTonerActionPerformed

    private void btnGravar_cadTonerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravar_cadTonerActionPerformed
        Toner toner = new Toner();

        toner.setModelo(entModelo.getText());
        toner.setNum_serie(entNs.getText());
        toner.setBp(Integer.parseInt(entBp.getText()));
        toner.setEmpresa((entEmpresa.getText()));
        toner.setPreco(Double.parseDouble(entPreco.getText()));
        toner.setTipoToner(entTipoToner.getSelectedItem().toString());

        // Validação de dados
        if ((entModelo.getText().isEmpty()) || (entNs.getText().isEmpty()) || (Integer.parseInt(entBp.getText()) == 0) || (entEmpresa.getText().isEmpty()) || (Double.parseDouble(entPreco.getText()) == 0) || (entTipoToner.getSelectedItem().toString()).isEmpty()) {
            JOptionPane.showMessageDialog(null, "O preenchimento de todos os campos é obrigatório!");
        } else { // instanciando a classe*/
            TonerDAO dao = new TonerDAO();
            dao.cadastrarToner(toner);
            JOptionPane.showMessageDialog(null, "Toner cadastrado com sucesso!");
        }

        entModelo.setText("");
        entNs.setText("");
        entBp.setText("");
        entEmpresa.setText("");
        entPreco.setText("");
        entTipoToner.setSelectedItem("-");

    }//GEN-LAST:event_btnGravar_cadTonerActionPerformed

    private void btnCancelar_cadTonerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar_cadTonerActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelar_cadTonerActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JCadastrarToner().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar_cadToner;
    private javax.swing.JButton btnGravar_cadToner;
    private javax.swing.JTextField entBp;
    private javax.swing.JTextField entEmpresa;
    private javax.swing.JTextField entId;
    private javax.swing.JTextField entModelo;
    private javax.swing.JTextField entNs;
    private javax.swing.JTextField entPreco;
    private javax.swing.JComboBox<String> entTipoToner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables

}
