/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.ajuda;

import java.awt.Desktop;
import javax.swing.event.HyperlinkEvent;
import javax.swing.event.HyperlinkListener;

/**
 *
 * @author Rafael
 */
public class AjudaSobre extends javax.swing.JInternalFrame {

    /**
     * Creates new form JanelaSobre
     */
    public AjudaSobre() {
        initComponents();
        
        
        this.jTextPane1.addHyperlinkListener(new HyperlinkListener() {
                    @Override
                    public void hyperlinkUpdate(HyperlinkEvent hle) {
                        if (HyperlinkEvent.EventType.ACTIVATED.equals(hle.getEventType())) {
                            System.out.println(hle.getURL());
                            Desktop desktop = Desktop.getDesktop();
                            try {
                                desktop.browse(hle.getURL().toURI());
                            } catch (Exception ex) {
                                ex.printStackTrace();
                            }
                        }
                    }
                });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setClosable(true);
        setTitle("Sobre");
        setPreferredSize(new java.awt.Dimension(400, 280));

        jTextPane1.setEditable(false);
        jTextPane1.setContentType("text/html"); // NOI18N
        jTextPane1.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jTextPane1.setText("<html>\n<head>\n</head>\n<body>\n\t<p style=\"margin-top: 5px\">\n\t\tDesenvolvido por:\n\t</p>\n\t<p style=\"margin-top: 5px; margin-left:10px\">\n\t\tDiego Cruz (<a href=\"https://github.com/diegocruzalves\">Github</a> | <a href=\"mailto:diegocruzalves@gmail.com\">Gmail</a>)\n\t</p>\n\t<p style=\"margin-top: 5px; margin-left:10px\">\n\t\tRafael Paixão (<a href=\"https://github.com/rafaelpaixao\">Github</a> | <a href=\"mailto:rafaelsspaixao@gmail.com\">Gmail</a>)\n\t</p>\n\t<p style=\"margin-top: 15px\">\n\t\tSistema para controle de toner desenvolvido como projeto final para a disciplina Linguagens e Técnicas de Programação I, sob orientação do professor Jairo Rego, para o curso Bacharelado em Sistema de Informação da Universidade Salvador (UNIFACS).\n\t</p>\n\t<p style=\"margin-top: 15px\">\n\t\tFeira de Santana, Dezembro/2016.\n\t</p>\n</body>\n</html>");
        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );

        setBounds(300, 100, 400, 280);
    }// </editor-fold>//GEN-END:initComponents


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables


}
